<?php

namespace ContainerFVOIKYF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2PKNHsYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2PKNHsY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2PKNHsY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator..TnixTc', 'get_ServiceLocator__TnixTcService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator..8FI4NL', 'get_ServiceLocator__8FI4NLService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.CJ1yQX6', 'get_ServiceLocator_CJ1yQX6Service', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.GjE0bdT', 'get_ServiceLocator_GjE0bdTService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.Wqurr1r', 'get_ServiceLocator_Wqurr1rService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.LBiO.oa', 'get_ServiceLocator_LBiO_OaService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator..TnixTc', 'get_ServiceLocator__TnixTcService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator..8FI4NL', 'get_ServiceLocator__8FI4NLService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.CJ1yQX6', 'get_ServiceLocator_CJ1yQX6Service', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.GjE0bdT', 'get_ServiceLocator_GjE0bdTService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.Wqurr1r', 'get_ServiceLocator_Wqurr1rService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.LBiO.oa', 'get_ServiceLocator_LBiO_OaService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
