<?php

namespace ContainerFVOIKYF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wqurr1rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wqurr1r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wqurr1r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'product' => ['privates', '.errored..service_locator.Wqurr1r.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.Wqurr1r": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'manager' => '?',
            'product' => 'App\\Entity\\Product',
            'repository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
