<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVXW9pgS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVXW9pgS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVXW9pgS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVXW9pgS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVXW9pgS\App_KernelDevDebugContainer([
    'container.build_hash' => 'VXW9pgS',
    'container.build_id' => '2b288951',
    'container.build_time' => 1683138991,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVXW9pgS');
