<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9SLx75x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9SLx75x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9SLx75x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9SLx75x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9SLx75x\App_KernelDevDebugContainer([
    'container.build_hash' => '9SLx75x',
    'container.build_id' => '383ae15a',
    'container.build_time' => 1683218019,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9SLx75x');
